name: Check IaaS Ready

on:
  workflow_dispatch:
    inputs:
      workflows:
        description: "Comma-separated workflow filenames to check"
        required: true
        type: string
      branch:
        description: "Branch to check"
        default: main
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check workflows status
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WORKFLOWS: ${{ inputs.workflows }}
        BRANCH: ${{ inputs.branch }}
        REPO: ${{ github.repository }}
      run: |-
        .github/scripts/check-iaas-ready_check_check-workflows-status.sh
